# Lume Configuration

defaultLocationName: "default"
cacheDirectory: "/Users/camdennarzt/Library/Caches/lume"
cachingEnabled: true

# VM Locations
vmLocations:
  - name: "default"
    path: "~/.lume"
